#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")

export DEV_UID=`id -u`
export DEV_GID=`id -g`
export WHOAMI=`whoami`
export PROJECT_PATH=$(dirname "$SCRIPT")
export PROJECT_NAME=$(basename "$PROJECT_PATH")
export TERM=linux

docker-compose "$@"
