### Notes
#
# - using the 'build' config instead of 'image' allows to build the stack with just 'docker-compose build'
# - SYS_PTRACE capability is needed to allow the containers to read /proc/$PID, which is needed by init scripts
# - The docker-compose 'service' name corresponds to the top-level yml keys
# - The container name is used in most 'docker' commands (Ex : docker exec -ti kaliop_cli su site)
#  Keeping a separate container name for each project allows to run many container platforms in parallel
# - The hostname key is used by Docker internal DNS to reach other containers
# Ex : the host backend in your Varnish vcl file  must be "web_backend" if your web service hostname is "web_backend"
#
version: "2.1"
services:
    web:
        build:
            context: docker/apache
        hostname: web
        container_name: todolist_web
        ports:
            - "80:80"
        volumes:
            - "./docker/apache/004-dynamic-vhost.conf:/etc/apache2/sites-available/004-dynamic-vhost.conf"
            - "./docker/apache/ez5-common.conf:/etc/apache2/sites-available/ez5-common.conf"
            - "${PROJECT_PATH}:/var/www:rw"
        cap_add:
            - SYS_PTRACE
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
        networks:
            - default
        depends_on:
            - memcached

    cli:
        build:
            context: docker/php
        hostname: cli
        container_name: todolist_cli
        privileged: true
        user: ${DEV_UID:-1000}:${DEV_GID:-1000}
        volumes:
            - "$SSH_AUTH_SOCK:/ssh-agent:ro"
            - "~/.gitconfig:/home/site/.gitconfig:ro"
            - "~/.ssh/config:/home/site/.ssh/config:ro"
            - "${PROJECT_PATH}:/var/www:rw"
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
            - TERM=xterm-color
        cap_add:
            - SYS_PTRACE
        networks:
            - default
        depends_on:
            - memcached

    memcached:
        image: klabs/memcached
        hostname:  memcached
        container_name: csa_memcached
        cap_add:
            - SYS_PTRACE
        networks:
            - default

networks:
    default:
        ipam:
          driver: default
          config:
          -
            subnet: 192.168.51.0/24